# Generated by Django 4.1 on 2022-08-18 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_f_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('author_l_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('author_email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 3, 55, 972147, tzinfo=datetime.timezone.utc), verbose_name='Time of creation')),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('post_title', models.CharField(max_length=600, verbose_name='Title')),
                ('post_main', models.TextField(verbose_name="Post's main body")),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=600, verbose_name='Comment Title')),
                ('nickname', models.CharField(max_length=100, verbose_name='UserName')),
                ('comment_content', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 3, 55, 972147, tzinfo=datetime.timezone.utc))),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='my_blog.post')),
            ],
        ),
    ]
