# Generated by Django 4.1 on 2022-08-18 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_alter_comment_create_date_alter_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 14, 19, 692878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 22, 14, 19, 692878, tzinfo=datetime.timezone.utc), verbose_name='Time of creation'),
        ),
    ]
