# Generated by Django 4.1 on 2022-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_alter_comment_create_date_alter_post_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
