# Generated by Django 4.1 on 2022-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Is this a Draft?(check the box if YES)'),
        ),
    ]
