# Generated by Django 4.1 on 2022-08-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0012_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
