# Generated by Django 4.1 on 2022-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0016_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=600, verbose_name='Title'),
        ),
    ]
