# Generated by Django 4.1 on 2022-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0017_alter_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Leave a Comment...'),
        ),
    ]
