# Generated by Django 4.1 on 2022-09-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0018_alter_comment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
